custom_login/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'login'

urlpatterns = [
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('', views.Dashboard, name='dashboard'),
    path('logout/', views.Logout, name='logout'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('password-reset/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='custom_login/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='custom_login/password_reset_complete.html'),
         name='password_reset_complete'),
]

login/urls.py
from django.contrib import admin
from django.urls import path, include
from custom_login.admin import custom_site
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('custom_admin/', custom_site.urls),
    path('custom_login/', include('custom_login.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

custom_login/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import ugettext_lazy as _


class CustomUserManager(BaseUserManager):
    """custom user manager class"""
    use_in_migration = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)
        

class User(AbstractBaseUser, PermissionsMixin):
    """ Custom user model class"""
    email = models.EmailField(('email'), unique=True, default='')
    name = models.CharField(('name'), max_length=50, blank=False)
    is_superadmin = models.BooleanField(_('is_superadmin'), default=False)
    is_active = models.BooleanField(_('is_active'), default=True)
    is_staff = models.BooleanField(default=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']
    objects = CustomUserManager()

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        """stirng representation"""
        return self.email



# IPL Team WorkOut Model

class Tags(models.Model):
    name = models.CharField(max_length=250)
    
    
class Exercise(models.Model):
    name = models.CharField(max_length=250)
    tags = models.ManyToManyField(Tags)

class Workout_Exercise(models.Model):
    workout = models.ForeignKey( 'Workout', on_delete=models.CASCADE,)
    exercise = models.ForeignKey( Exercise, on_delete=models.CASCADE,)
    reps = models.IntegerField()
    sets = models.IntegerField()
    weight = models.DecimalField(max_digits=6, decimal_places=2)


class Workout(models.Model):
    name = models.CharField(max_length=100)
    body_weight = models.DecimalField(max_digits=6, decimal_places=2)
    date = models.DateTimeField(auto_now_add=True)
    exercises = models.ManyToManyField(Exercise, through=Workout_Exercise)

custom_login/forms.py
from django import forms
from django.contrib.auth import get_user_model


class SignupForm(forms.ModelForm):
    """user signup form"""
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = get_user_model()
        fields = ('email', 'name', 'password',)


class LoginForm(forms.Form):
    """user login form"""
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())

custom_login/views.py
from datetime import date, timedelta
from django.shortcuts import render, redirect
from django.views.generic.edit import FormView
from . import forms
from django.contrib.auth import login, authenticate, logout
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin


class SignupView(FormView):
    form_class = forms.SignupForm
    template_name= 'custom_login/signup.html'
    success_url= reverse_lazy('dashboard')
    password_reset=reverse_lazy('pass_reset')

    def form_valid(self, form):
        user=form.save(commit=False)
        user.save()
        login(self.request, user)
        if user is not None:
            if user.is_active:
                if date.today() - user.password_date > timedelta(days=90):
                    return HttpResponseRedirect(self.password_reset)
                return HttpResponseRedirect(self.success_url)

        return super().form_valid(form)

def Dashboard(request):
    """ make dashboard view """
    return render(request, 'custom_login/dashboard.html')


def Logout(request):
    """logout logged in user"""
    logout(request)
    return HttpResponseRedirect(reverse_lazy('login:dashboard'))


class LoginView(FormView):
    """login view"""

    form_class = forms.LoginForm
    success_url = reverse_lazy('login:dashboard')
    template_name = 'custom_login/login.html'

    def form_valid(self, form):
        """ process user login"""
        credentials = form.cleaned_data

        user = authenticate(username=credentials['email'],
                            password=credentials['password'])

        if user is not None:
            login(self.request, user)
            return HttpResponseRedirect(self.success_url)

        else:
            messages.add_message(self.request, messages.INFO, 'Wrong credentials\
                                please try again')
            return HttpResponseRedirect(reverse_lazy('login'))

class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'custom_login/password_reset.html'
    email_template_name = 'custom_login/password_reset_email.html'
   
    success_message = "We've emailed you instructions for setting your password, " \
                      "if an account exists with the email you entered. You should receive them shortly." \
                      " If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = reverse_lazy('login:dashboard')

templates/base.html
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Custom Login{% endblock %}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script></head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/custom_login/admin/admin_login.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" 
href="{% static "custom_login/admin/login.css" %}">
{{ form.media }}
{% endblock %}

{% block bodyclass %}{{ block.super }} login  {% endblock %}

{% block usertools %}{% endblock %}

{% block nav-global %}{% endblock %}

{% block nav-sidebar %}{% endblock %}

{% block content_title %}{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
{% if form.errors and not form.non_field_errors %}
<p class="errornote">
{% if form.errors.items|length == 1 %}{% translate "Please correct the error below." %}{% else %}{% translate "Please correct the errors below." %}{% endif %}
</p>
{% endif %}

{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<p class="errornote">
    {{ error }}
</p>
{% endfor %}
{% endif %}

<div id="content-main">

{% if user.is_authenticated %}
<p class="errornote">
{% blocktranslate trimmed %}
    You are authenticated as {{ username }}, but are not authorized to
    access this page. Would you like to login to a different account?
{% endblocktranslate %}
</p>
{% endif %}

<form action="{{ app_path }}" method="post" id="login-form">{% csrf_token %}
  <div class="form-row">
    {{ form.username.errors }}
    {{ form.username.label_tag }} {{ form.username }}
  </div>
  <div class="form-row">
    {{ form.password.errors }}
    {{ form.password.label_tag }} {{ form.password }}
    <input type="hidden" name="next" value="{{ next }}">
  </div>
  {% url 'admin_password_reset' as password_reset_url %}
  {% if password_reset_url %}
  <div class="password-reset-link">
    <a href="{{ password_reset_url }}">{% translate 'Forgotten your password or username?' %}</a>
  </div>
  {% endif %}
  <div class="submit-row">
    <input type="submit" value="{% translate 'Click here to Login' %}">
  </div>
</form>

</div>
{% endblock %}

templates/custom_login/dashboard.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}DashBoard{% endblock %}

{% block content %}
<h2>Dash Board</h2>
{% csrf_token %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'login:logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login:login' %}">Log In</a> |
  <a href="{% url 'login:signup' %}">Sign Up</a>
{% endif %}
{% if password_change_required %}
<p class='help'>{% trans "Your password has expired. Please change it using the form below." %}</p>
{% endif %}
{% load crispy_forms_tags %}
<form action="." method="post">{% csrf_token %}
{{ form|crispy }}{% if next %}
<input type="hidden" name="next" value="{{ next }}" />{% endif %}
<input type="submit" value="Submit" />
</form>

{% endblock %}

templates/custom_login/login.html
{% block content %}
<h2>Log In</h2>
{% load crispy_forms_tags %}
<form method="post">
  {% csrf_token %}
  
  <!-- Email input -->
  <div class="form-outline mb-4">
    <div class="row">
      <div class="col-6">
        {{ form.email|as_crispy_field }}
      </div>
  </div>

  <!-- Password input -->
  <div class="form-outline mb-4">
    <div class="row">
      <div class="col-6">
        {{ form.password|as_crispy_field }}
      </div>
  </div>

  <!-- 2 column grid layout for inline styling -->
  <div class="row mb-4">
    <div class="col d-flex justify-content-center">
      <!-- Checkbox -->
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="form1Example3" checked />
        <label class="form-check-label" for="form1Example3"> Remember me </label>
      </div>


  <button type="submit">Log In</button>
</form>
<a href="{% url 'login:password_reset' %}"><i>Reset Password?</i></a>

{% endblock %}

templates/custom_login/password_reset.html
{% extends "base.html" %}
{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                            <div id="error_div"></div>
                          <h3 class="font-weight-light my-4 text-center">Forgot Password?</h3>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                      <label class="small mb-1" for="id_email">Email</label>
                                        <input type="email" name="email"  class="form-control"
                                               autocomplete="email" maxlength="254" required id="id_email"
                                               placeholder="Enter email">
                                    </div>
                                </div>
                            </div>
                                <div class="form-row">
                                  <div class="col-md-10 offset-md-1">
                                    <div class="form-group mt-0 mb-1">
                                        <button type="submit" class="col-md-12 btn btn-dark">Submit
                                        </button>
                                    </div>
                                 </div>
                               </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="{% url 'login:signup' %}">Create A New Account</a><br><br>
                                <a href="{% url 'login:login' %}">Back To Login</a><br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

  </div>
{% endblock content %}

templates/custom_login/password_reset_complete.html
{% extends "users/base.html" %}
{% block content %}
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="alert alert-info">
                        Your password has been set. You may go ahead and <a href="{% url 'login' %}">Login Here</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/custom_login/password_reset_confirm.html
{% extends "base.html" %}
{% block title %} Password Reset {% endblock title%}
{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    {% if validlink %}
                        <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                            <div class="card-header justify-content-center">
                              <h3 class="font-weight-light my-4 text-center">Reset Your Password</h3>
                            </div>
                            {% if form.errors %}
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <div id="form_errors">
                                        {% for key, value in form.errors.items %}
                                            <strong>{{ value }}</strong>
                                        {% endfor %}
                                    </div>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endif %}

                            <div class="card-body">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password1">New Password</label>
                                                <input type="password" name="new_password1" autocomplete="new-password"
                                                       class="form-control" required id="id_new_password1"
                                                       placeholder="Enter password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password2">New Password Confirmation</label>
                                                <input type="password" name="new_password2" autocomplete="new-password"
                                                       required id="id_new_password2" class="form-control"
                                                       placeholder="Confirm password"/>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group mt-0 mb-1">
                                                <button type="submit" class="col-md-12 btn btn-dark" id="reset">Reset Password</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    {% else %}
                    <div class="alert alert-warning">
                        The password reset link was invalid, possibly because it has already been used.
                        Please request a new password reset.
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/custom_login/password_reset_email.html
{% autoescape off %}
  To initiate the password reset process for your {{ user.email }} Django Registration/Login App Account,
  click the link below:

  {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.


{% endautoescape %}

templates/custom_login/password_reset_form.html
<h1> Forgot/change your password</h1>
<p> Enter your email address below</p>
{% load crispy_forms_tags %}
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit">Send</button>
</form>

templates/custom_login/signup.html
{% block content %}
<h2>Sign Up</h2>
{% load crispy_forms_tags %}
<form method="post">
  {% csrf_token %}
  
  <!-- Email input -->
  <div class="form-outline mb-4">
    <div class="row">
      <div class="col-6">
        {{ form.email|as_crispy_field }}
      </div>
  </div>
  <div class="form-outline mb-4">
    <div class="row">
      <div class="col-6">
        {{ form.name|as_crispy_field }}
      </div>
  </div>

  <!-- Password input -->
  <div class="form-outline mb-4">
    <div class="row">
      <div class="col-6">
        {{ form.password|as_crispy_field }}
      </div>
  </div>

 


  <button type="submit">Sign Up</button>
</form>
{% endblock %}